### ISSUE TITLE
Dominica Republic no found in country select

### ISSUE THREAD

**Issue by miguelcabreja90** [yogakurniawan/vue-tel-input-vuetify#30] opened 2020-10-15 05:27 UTC
I can't find the country Dominic Republic in the country select?

**Comment by mattbab** [comment] 2020-12-16 21:46
The Dominican Republic (as well as Puerto Rico and others) has a country code of +1 which overlaps with the US and Canada. This is a duplicate of #4.

**Closed** 2022-08-10 18:54 UTC
